//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/ManagerScripts/Input/ManagerIS.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ManagerIS: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ManagerIS()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ManagerIS"",
    ""maps"": [
        {
            ""name"": ""Manager"",
            ""id"": ""3cec9324-0bf6-4afc-adfb-2d8a33acb13b"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""df77260f-d839-4134-9ccc-3390c51b3cd2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""70d718bf-cb86-4bb2-9336-7c40a3cf0faf"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9e2a00b-9bb1-4f9e-a723-34101a22f86e"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Manager
        m_Manager = asset.FindActionMap("Manager", throwIfNotFound: true);
        m_Manager_Pause = m_Manager.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Manager
    private readonly InputActionMap m_Manager;
    private List<IManagerActions> m_ManagerActionsCallbackInterfaces = new List<IManagerActions>();
    private readonly InputAction m_Manager_Pause;
    public struct ManagerActions
    {
        private @ManagerIS m_Wrapper;
        public ManagerActions(@ManagerIS wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_Manager_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Manager; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ManagerActions set) { return set.Get(); }
        public void AddCallbacks(IManagerActions instance)
        {
            if (instance == null || m_Wrapper.m_ManagerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ManagerActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IManagerActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IManagerActions instance)
        {
            if (m_Wrapper.m_ManagerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IManagerActions instance)
        {
            foreach (var item in m_Wrapper.m_ManagerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ManagerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ManagerActions @Manager => new ManagerActions(this);
    public interface IManagerActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
